# -*- coding: utf-8 -*-
"""
データベース接続とスキーマ初期化
"""

import os
import sqlite3
from urllib.parse import urlparse

# ---- psycopg2 の有無 ----
try:
    import psycopg2
except Exception:
    psycopg2 = None


def _is_pg(conn) -> bool:
    """PostgreSQL/SQLite 判定"""
    return conn.__class__.__module__.startswith("psycopg2")


def _sql(conn, text: str) -> str:
    """プレースホルダ統一（PostgreSQL: %s ／ SQLite: ?）"""
    return text if _is_pg(conn) else text.replace("%s", "?")


def get_db_connection():
    """
    データベース接続を返す（get_dbのエイリアス）
    """
    return get_db()


def get_db():
    """
    優先順位：
      1) .env/環境変数の DATABASE_URL
      2) ローカル Postgres accounting_dev (postgres / n-N31415926!!)
      3) SQLite
    戻り値: DB接続オブジェクト
    """
    db_url = os.environ.get("DATABASE_URL")
    if not db_url:
        db_url = "postgresql://postgres:n-N31415926!!@localhost:5432/accounting_dev"

    # --- Try PostgreSQL ---
    if psycopg2:
        try:
            url = urlparse(db_url)
            sslmode = "disable" if (url.hostname in ("localhost", "127.0.0.1")) else "require"
            conn = psycopg2.connect(
                dbname=url.path[1:],
                user=url.username,
                password=url.password,
                host=url.hostname,
                port=url.port,
                sslmode=sslmode,
                application_name="login_system"
            )
            conn.autocommit = True
            print(f"✅ PostgreSQL 接続成功: {url.hostname}:{url.port}/{url.path[1:]}")
            init_schema(conn)           # スキーマ自動作成
            return conn
        except Exception as e:
            print(f"⚠️ PostgreSQL接続失敗 → SQLiteへフォールバック: {e}")

    # --- SQLite フォールバック ---
    os.makedirs("database", exist_ok=True)
    conn = sqlite3.connect("database/login_auth.db", detect_types=sqlite3.PARSE_DECLTYPES)
    conn.row_factory = sqlite3.Row
    print("⚠️ SQLite にフォールバック: database/login_auth.db")
    init_schema(conn)
    return conn


def init_schema(conn):
    """
    PostgreSQL / SQLite 共通のスキーマ初期化
    - T_管理者（system_admin / tenant_admin / admin ログイン用）
    - T_従業員（employee ログイン用）
    - T_テナント（tenant_admin 管理用）
    """
    cur = conn.cursor()

    # ---- T_管理者 ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_管理者"(
            id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            login_id         TEXT UNIQUE NOT NULL,
            name             TEXT NOT NULL,
            password_hash    TEXT NOT NULL,
            role             TEXT DEFAULT 'admin',
            tenant_id        INTEGER,
            active           INTEGER DEFAULT 1,
            is_owner         INTEGER DEFAULT 0,
            can_manage_admins INTEGER DEFAULT 0,
            created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_管理者"(
            id               INTEGER PRIMARY KEY AUTOINCREMENT,
            login_id         TEXT UNIQUE NOT NULL,
            name             TEXT NOT NULL,
            password_hash    TEXT NOT NULL,
            role             TEXT DEFAULT 'admin',
            tenant_id        INTEGER,
            active           INTEGER DEFAULT 1,
            is_owner         INTEGER DEFAULT 0,
            can_manage_admins INTEGER DEFAULT 0,
            created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')

    # ---- T_従業員 ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_従業員"(
            id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email         TEXT UNIQUE NOT NULL,
            login_id      TEXT UNIQUE NOT NULL,
            name          TEXT NOT NULL,
            password_hash TEXT,
            tenant_id     INTEGER,
            role          TEXT DEFAULT 'employee',
            created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_従業員"(
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            email         TEXT UNIQUE NOT NULL,
            login_id      TEXT UNIQUE NOT NULL,
            name          TEXT NOT NULL,
            password_hash TEXT,
            tenant_id     INTEGER,
            role          TEXT DEFAULT 'employee',
            created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')

    # ---- T_テナント ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_テナント"(
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            名称        TEXT NOT NULL,
            slug        TEXT UNIQUE NOT NULL,
            有効        INTEGER DEFAULT 1,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_テナント"(
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            名称        TEXT NOT NULL,
            slug        TEXT UNIQUE NOT NULL,
            有効        INTEGER DEFAULT 1,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')

    # ---- T_店舗 ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_店舗"(
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id   INTEGER NOT NULL,
            名称        TEXT NOT NULL,
            slug        TEXT NOT NULL,
            有効        INTEGER DEFAULT 1,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(tenant_id, slug)
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_店舗"(
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            tenant_id   INTEGER NOT NULL,
            名称        TEXT NOT NULL,
            slug        TEXT NOT NULL,
            有効        INTEGER DEFAULT 1,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(tenant_id, slug)
        )''')

    # ---- T_テナント管理者_テナント (多対多関係) ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_テナント管理者_テナント"(
            id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_admin_id     INTEGER NOT NULL,
            tenant_id           INTEGER NOT NULL,
            created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(tenant_admin_id, tenant_id)
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_テナント管理者_テナント"(
            id                  INTEGER PRIMARY KEY AUTOINCREMENT,
            tenant_admin_id     INTEGER NOT NULL,
            tenant_id           INTEGER NOT NULL,
            created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(tenant_admin_id, tenant_id)
        )''')

    # ---- T_管理者_店舗 (多対多関係) ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_管理者_店舗"(
            id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            admin_id    INTEGER NOT NULL,
            store_id    INTEGER NOT NULL,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(admin_id, store_id)
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_管理者_店舗"(
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            admin_id    INTEGER NOT NULL,
            store_id    INTEGER NOT NULL,
            created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(admin_id, store_id)
        )''')

    # ---- T_従業員_店舗 (多対多関係) ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_従業員_店舗"(
            id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            employee_id     INTEGER NOT NULL,
            store_id        INTEGER NOT NULL,
            created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(employee_id, store_id)
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_従業員_店舗"(
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            employee_id     INTEGER NOT NULL,
            store_id        INTEGER NOT NULL,
            created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(employee_id, store_id)
        )''')

    # ---- T_証憑 (レシート・領収書データ) ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_証憑"(
            id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id           INTEGER NOT NULL,
            uploaded_by         INTEGER NOT NULL,
            画像パス            TEXT,
            画像URL             TEXT,
            OCR結果_生データ    TEXT,
            電話番号            TEXT,
            住所                TEXT,
            金額                NUMERIC(15, 2),
            日付                DATE,
            摘要                TEXT,
            ステータス          TEXT DEFAULT 'pending',
            created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_証憑"(
            id                  INTEGER PRIMARY KEY AUTOINCREMENT,
            tenant_id           INTEGER NOT NULL,
            uploaded_by         INTEGER NOT NULL,
            画像パス            TEXT,
            画像URL             TEXT,
            OCR結果_生データ    TEXT,
            電話番号            TEXT,
            住所                TEXT,
            金額                REAL,
            日付                TEXT,
            摘要                TEXT,
            ステータス          TEXT DEFAULT 'pending',
            created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')

    # ---- T_企業情報 (国税庁APIから取得) ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_企業情報"(
            id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id               INTEGER NOT NULL,
            法人番号                TEXT,
            インボイス登録番号      TEXT UNIQUE,
            会社名                  TEXT NOT NULL,
            会社名カナ              TEXT,
            郵便番号                TEXT,
            住所                    TEXT,
            電話番号                TEXT,
            事業概要                TEXT,
            インボイス登録有無      INTEGER DEFAULT 0,
            インボイス登録日        DATE,
            最終更新日              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_企業情報"(
            id                      INTEGER PRIMARY KEY AUTOINCREMENT,
            tenant_id               INTEGER NOT NULL,
            法人番号                TEXT,
            インボイス登録番号      TEXT UNIQUE,
            会社名                  TEXT NOT NULL,
            会社名カナ              TEXT,
            郵便番号                TEXT,
            住所                    TEXT,
            電話番号                TEXT,
            事業概要                TEXT,
            インボイス登録有無      INTEGER DEFAULT 0,
            インボイス登録日        TEXT,
            最終更新日              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')

    # ---- T_仕訳 (自動生成された仕訳データ) ----
    if _is_pg(conn):
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_仕訳"(
            id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id           INTEGER NOT NULL,
            証憑ID              INTEGER,
            企業情報ID          INTEGER,
            日付                DATE NOT NULL,
            借方勘定科目        TEXT NOT NULL,
            借方金額            NUMERIC(15, 2) NOT NULL,
            借方補助科目        TEXT,
            貸方勘定科目        TEXT NOT NULL,
            貸方金額            NUMERIC(15, 2) NOT NULL,
            貸方補助科目        TEXT,
            摘要                TEXT,
            自動生成フラグ      INTEGER DEFAULT 1,
            確認済みフラグ      INTEGER DEFAULT 0,
            created_by          INTEGER NOT NULL,
            created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')
    else:
        cur.execute('''
        CREATE TABLE IF NOT EXISTS "T_仕訳"(
            id                  INTEGER PRIMARY KEY AUTOINCREMENT,
            tenant_id           INTEGER NOT NULL,
            証憑ID              INTEGER,
            企業情報ID          INTEGER,
            日付                TEXT NOT NULL,
            借方勘定科目        TEXT NOT NULL,
            借方金額            REAL NOT NULL,
            借方補助科目        TEXT,
            貸方勘定科目        TEXT NOT NULL,
            貸方金額            REAL NOT NULL,
            貸方補助科目        TEXT,
            摘要                TEXT,
            自動生成フラグ      INTEGER DEFAULT 1,
            確認済みフラグ      INTEGER DEFAULT 0,
            created_by          INTEGER NOT NULL,
            created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )''')

    if not _is_pg(conn):
        conn.commit()
